### ISSUE TITLE
Automatically publish this web application on successful build

### ISSUE THREAD

**Issue by markafitzgerald1** [markafitzgerald1/cribbage-analyst#29]
It would be helpful to potential users and code readers to be able to see and interact with (i.e. not just screenshots) what this webapp actually does.

**Comment by markafitzgerald1** [comment]
This can be done with [gh-pages](https://www.npmjs.com/package/gh-pages) once the Gulp pipeline copies `index.html` to `dist/`!

**Comment by markf-hubdoc-com** [comment]
Consider creating a follow-on issue to add site usage analytics to the published webapp once this issue is resolved.

**Comment by markafitzgerald1** [comment]
Consider creating a follow-on issue to add site usage analytics to the published webapp once this issue is resolved.

**Comment by markafitzgerald1** [comment]
Solution in a8628b30a630de2573d63eacacd4f47e74c7fdaa works from my development laptop but not from Travis CI as it does not have a user.email, user.name or GitHub user password or app-specific GitHub access token. Can probably resolve via steps like https://gist.github.com/auth/github/callback?return_to=https://gist.github.com/willprice/e07efd73fb7f13f917ea&browser_session_id=534dcb04715f1bb8d57451c7d57acfee37a1e1bb&code=1fbce64f7f9951ce7ca2&state=3a420fcf1de858868eefa1c5f779bfc2bd6262f9241e4eeea85edd3160fec469.

**Comment by markafitzgerald1** [comment]
How to create a token for a script - and hopefully TravisCI - to use: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/.

**Comment by markafitzgerald1** [comment]
Resolved as of 8059f3c.
