### ISSUE TITLE
Disambiguate Node.js LTS reference in README.md

### ISSUE THREAD

**Issue by markf-hubdoc-com** [markafitzgerald1/cribbage-analyst#31]
Could refer to three distinct versions of Node.js at present.

**Comment by markafitzgerald1** [comment]
Can now refer to only two Node.js versions.

**Comment by markafitzgerald1** [comment]
Fix candidate pushed to the [issue-31-disambiguate-readme-node-lts-reference](https://github.com/markafitzgerald1/cribbage-analyst/tree/issue-31-disambiguate-readme-node-lts-reference) branch in a9c3e3642f8022468eefaf9f2a503f1c1e0b72ce.

**Comment by markafitzgerald1** [comment]
Fix merged into `develop` and awaiting push to production with next release.

**Comment by markafitzgerald1** [comment]
Released to `master` in version `0.2.3`.
